/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.api;

import com.dtsre.api.v1.client.*;
import com.dtsre.api.v1.client.auth.*;
import com.dtsre.api.v1.client.model.AlertNotifyGroupCreateParam;
import com.dtsre.api.v1.client.model.AlertNotifyGroupUpdateParam;
import com.dtsre.api.v1.client.model.ROfboolean;
import com.dtsre.api.v1.client.model.ROflong;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AlertNotifyGroupApi
 */
public class AlertNotifyGroupApiTest {

    private final AlertNotifyGroupApi api = new AlertNotifyGroupApi();

    /**
     * 创建通知组
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNotifyGroupTest() throws ApiException {
        //AlertNotifyGroupCreateParam param = null;
        //ROflong response = api.createNotifyGroup(param);
        // TODO: test validations
    }

    /**
     * 修改通知组
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateNotifyGroupTest() throws ApiException {
        //AlertNotifyGroupUpdateParam param = null;
        //ROfboolean response = api.updateNotifyGroup(param);
        // TODO: test validations
    }

}
