/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.api;

import com.dtsre.api.v1.client.*;
import com.dtsre.api.v1.client.auth.*;
import com.dtsre.api.v1.client.model.ROfListOfAppVO;
import com.dtsre.api.v1.client.model.ROfTimeseriesVO;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppApi
 */
public class AppApiTest {

    private final AppApi api = new AppApi();

    /**
     * 应用列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAppsTest() throws ApiException {
        //ROfListOfAppVO response = api.listApps();
        // TODO: test validations
    }

    /**
     * 查询指标时间序列
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryAppMetricsTest() throws ApiException {
        //Long end = null;
        //List<String> measures = null;
        //String metric = null;
        //Long start = null;
        //List<String> dimensions = null;
        //String direction = null;
        //String filter = null;
        //Long interval = null;
        //Integer limit = null;
        //String sort = null;
        //ROfTimeseriesVO response = api.queryAppMetrics(end, measures, metric, start, dimensions, direction, filter, interval, limit, sort);
        // TODO: test validations
    }

}
