/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.api;

import com.dtsre.api.v1.client.*;
import com.dtsre.api.v1.client.auth.*;
import com.dtsre.api.v1.client.model.LogSearchParam;
import com.dtsre.api.v1.client.model.LogSendParam;
import com.dtsre.api.v1.client.model.ROfLogSearchVO;
import com.dtsre.api.v1.client.model.ROfboolean;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LogApi
 */
public class LogApiTest {

    private final LogApi api = new LogApi();

    /**
     * 日志查询
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchLogsTest() throws ApiException {
        //LogSearchParam param = null;
        //ROfLogSearchVO response = api.searchLogs(param);
        // TODO: test validations
    }

    /**
     * 日志上报
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendLogsTest() throws ApiException {
        //LogSendParam param = null;
        //ROfboolean response = api.sendLogs(param);
        // TODO: test validations
    }

}
