/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.api;

import com.dtsre.api.v1.client.*;
import com.dtsre.api.v1.client.auth.*;
import com.dtsre.api.v1.client.model.ROfListOfWebAppVO;
import com.dtsre.api.v1.client.model.ROfTimeseriesVO;
import com.dtsre.api.v1.client.model.ROfstring;
import com.dtsre.api.v1.client.model.WebAppCreateParam;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebAppApi
 */
public class WebAppApiTest {

    private final WebAppApi api = new WebAppApi();

    /**
     * 创建应用站点
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createWebAppTest() throws ApiException {
        //WebAppCreateParam param = null;
        //ROfstring response = api.createWebApp(param);
        // TODO: test validations
    }

    /**
     * 应用列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listWebAppsTest() throws ApiException {
        //ROfListOfWebAppVO response = api.listWebApps();
        // TODO: test validations
    }

    /**
     * 查询指标时间序列
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryWebAppMetricsTest() throws ApiException {
        //Long end = null;
        //List<String> measures = null;
        //String metric = null;
        //Long start = null;
        //List<String> dimensions = null;
        //String direction = null;
        //String filter = null;
        //Long interval = null;
        //Integer limit = null;
        //String sort = null;
        //ROfTimeseriesVO response = api.queryWebAppMetrics(end, measures, metric, start, dimensions, direction, filter, interval, limit, sort);
        // TODO: test validations
    }

}
