/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.model;

import com.dtsre.api.v1.client.model.AlertNotifyUpdateParam;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AlertUpdateParam
 */
public class AlertUpdateParamTest {
    private final AlertUpdateParam model = new AlertUpdateParam();

    /**
     * Model tests for AlertUpdateParam
     */
    @Test
    public void testAlertUpdateParam() {
        // TODO: test AlertUpdateParam
    }

    /**
     * Test the property 'alertNotifies'
     */
    @Test
    public void alertNotifiesTest() {
        // TODO: test alertNotifies
    }

    /**
     * Test the property 'alertType'
     */
    @Test
    public void alertTypeTest() {
        // TODO: test alertType
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'notifyRecovered'
     */
    @Test
    public void notifyRecoveredTest() {
        // TODO: test notifyRecovered
    }

    /**
     * Test the property 'recoverNotification'
     */
    @Test
    public void recoverNotificationTest() {
        // TODO: test recoverNotification
    }

    /**
     * Test the property 'tagSet'
     */
    @Test
    public void tagSetTest() {
        // TODO: test tagSet
    }

    /**
     * Test the property 'triggerRule'
     */
    @Test
    public void triggerRuleTest() {
        // TODO: test triggerRule
    }

}
