/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DataPermission
 */
public class DataPermissionTest {
    private final DataPermission model = new DataPermission();

    /**
     * Model tests for DataPermission
     */
    @Test
    public void testDataPermission() {
        // TODO: test DataPermission
    }

    /**
     * Test the property 'all'
     */
    @Test
    public void allTest() {
        // TODO: test all
    }

    /**
     * Test the property 'permissionId'
     */
    @Test
    public void permissionIdTest() {
        // TODO: test permissionId
    }

    /**
     * Test the property 'tagSet'
     */
    @Test
    public void tagSetTest() {
        // TODO: test tagSet
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
