/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LogSearchParam
 */
public class LogSearchParamTest {
    private final LogSearchParam model = new LogSearchParam();

    /**
     * Model tests for LogSearchParam
     */
    @Test
    public void testLogSearchParam() {
        // TODO: test LogSearchParam
    }

    /**
     * Test the property 'appnames'
     */
    @Test
    public void appnamesTest() {
        // TODO: test appnames
    }

    /**
     * Test the property 'end'
     */
    @Test
    public void endTest() {
        // TODO: test end
    }

    /**
     * Test the property 'pageNumber'
     */
    @Test
    public void pageNumberTest() {
        // TODO: test pageNumber
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'queryText'
     */
    @Test
    public void queryTextTest() {
        // TODO: test queryText
    }

    /**
     * Test the property 'selectFields'
     */
    @Test
    public void selectFieldsTest() {
        // TODO: test selectFields
    }

    /**
     * Test the property 'sort'
     */
    @Test
    public void sortTest() {
        // TODO: test sort
    }

    /**
     * Test the property 'start'
     */
    @Test
    public void startTest() {
        // TODO: test start
    }

}
