/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LogVO
 */
public class LogVOTest {
    private final LogVO model = new LogVO();

    /**
     * Model tests for LogVO
     */
    @Test
    public void testLogVO() {
        // TODO: test LogVO
    }

    /**
     * Test the property 'appname'
     */
    @Test
    public void appnameTest() {
        // TODO: test appname
    }

    /**
     * Test the property 'hostname'
     */
    @Test
    public void hostnameTest() {
        // TODO: test hostname
    }

    /**
     * Test the property 'ip'
     */
    @Test
    public void ipTest() {
        // TODO: test ip
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'atTimestamp'
     */
    @Test
    public void atTimestampTest() {
        // TODO: test atTimestamp
    }

    /**
     * Test the property 'collectTime'
     */
    @Test
    public void collectTimeTest() {
        // TODO: test collectTime
    }

    /**
     * Test the property 'contextSeq'
     */
    @Test
    public void contextSeqTest() {
        // TODO: test contextSeq
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'receiveTimestamp'
     */
    @Test
    public void receiveTimestampTest() {
        // TODO: test receiveTimestamp
    }

    /**
     * Test the property 'customFields'
     */
    @Test
    public void customFieldsTest() {
        // TODO: test customFields
    }

    /**
     * Test the property 'customTags'
     */
    @Test
    public void customTagsTest() {
        // TODO: test customTags
    }

    /**
     * Test the property 'sysFields'
     */
    @Test
    public void sysFieldsTest() {
        // TODO: test sysFields
    }

    /**
     * Test the property 'sysTags'
     */
    @Test
    public void sysTagsTest() {
        // TODO: test sysTags
    }

}
