/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.model;

import com.dtsre.api.v1.client.model.TenantUserListVo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PagerOfTenantUserListVo
 */
public class PagerOfTenantUserListVoTest {
    private final PagerOfTenantUserListVo model = new PagerOfTenantUserListVo();

    /**
     * Model tests for PagerOfTenantUserListVo
     */
    @Test
    public void testPagerOfTenantUserListVo() {
        // TODO: test PagerOfTenantUserListVo
    }

    /**
     * Test the property 'currentPageNumber'
     */
    @Test
    public void currentPageNumberTest() {
        // TODO: test currentPageNumber
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'hasNext'
     */
    @Test
    public void hasNextTest() {
        // TODO: test hasNext
    }

    /**
     * Test the property 'hasPrev'
     */
    @Test
    public void hasPrevTest() {
        // TODO: test hasPrev
    }

    /**
     * Test the property 'perPageSize'
     */
    @Test
    public void perPageSizeTest() {
        // TODO: test perPageSize
    }

    /**
     * Test the property 'totalElements'
     */
    @Test
    public void totalElementsTest() {
        // TODO: test totalElements
    }

    /**
     * Test the property 'totalPages'
     */
    @Test
    public void totalPagesTest() {
        // TODO: test totalPages
    }

}
