/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.dtsre.api.v1.client.model.AlertNotifyUpdateParam;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.dtsre.api.v1.client.JSON;


/**
 * AlertUpdateParam
 */
@JsonPropertyOrder({
  AlertUpdateParam.JSON_PROPERTY_ALERT_NOTIFIES,
  AlertUpdateParam.JSON_PROPERTY_ALERT_TYPE,
  AlertUpdateParam.JSON_PROPERTY_CONTENT,
  AlertUpdateParam.JSON_PROPERTY_ID,
  AlertUpdateParam.JSON_PROPERTY_NAME,
  AlertUpdateParam.JSON_PROPERTY_NOTIFY_RECOVERED,
  AlertUpdateParam.JSON_PROPERTY_RECOVER_NOTIFICATION,
  AlertUpdateParam.JSON_PROPERTY_TAG_SET,
  AlertUpdateParam.JSON_PROPERTY_TRIGGER_RULE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-19T14:34:25.795+08:00[Asia/Shanghai]")
public class AlertUpdateParam {
  public static final String JSON_PROPERTY_ALERT_NOTIFIES = "alertNotifies";
  private List<AlertNotifyUpdateParam> alertNotifies = new ArrayList<>();

  /**
   * 告警类型:METRIC-指标告警，STATUS-状态告警，KEYWORD-关键词告警，CUSTOM-自定义告警
   */
  public enum AlertTypeEnum {
    METRIC("METRIC"),
    
    STATUS("STATUS"),
    
    KEYWORD("KEYWORD"),
    
    CUSTOM("CUSTOM"),
    
    WATER("WATER"),
    
    APPSTAT("APPSTAT"),
    
    WEBSTAT("WEBSTAT"),
    
    CBOS("CBOS");

    private String value;

    AlertTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AlertTypeEnum fromValue(String value) {
      for (AlertTypeEnum b : AlertTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ALERT_TYPE = "alertType";
  private AlertTypeEnum alertType;

  public static final String JSON_PROPERTY_CONTENT = "content";
  private String content;

  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_NOTIFY_RECOVERED = "notifyRecovered";
  private Boolean notifyRecovered;

  public static final String JSON_PROPERTY_RECOVER_NOTIFICATION = "recoverNotification";
  private String recoverNotification;

  public static final String JSON_PROPERTY_TAG_SET = "tagSet";
  private List<String> tagSet = null;

  public static final String JSON_PROPERTY_TRIGGER_RULE = "triggerRule";
  private Object triggerRule;

  public AlertUpdateParam() { 
  }

  public AlertUpdateParam alertNotifies(List<AlertNotifyUpdateParam> alertNotifies) {
    this.alertNotifies = alertNotifies;
    return this;
  }

  public AlertUpdateParam addAlertNotifiesItem(AlertNotifyUpdateParam alertNotifiesItem) {
    this.alertNotifies.add(alertNotifiesItem);
    return this;
  }

   /**
   * 通知规则
   * @return alertNotifies
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "通知规则")
  @JsonProperty(JSON_PROPERTY_ALERT_NOTIFIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<AlertNotifyUpdateParam> getAlertNotifies() {
    return alertNotifies;
  }


  @JsonProperty(JSON_PROPERTY_ALERT_NOTIFIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAlertNotifies(List<AlertNotifyUpdateParam> alertNotifies) {
    this.alertNotifies = alertNotifies;
  }


  public AlertUpdateParam alertType(AlertTypeEnum alertType) {
    this.alertType = alertType;
    return this;
  }

   /**
   * 告警类型:METRIC-指标告警，STATUS-状态告警，KEYWORD-关键词告警，CUSTOM-自定义告警
   * @return alertType
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "告警类型:METRIC-指标告警，STATUS-状态告警，KEYWORD-关键词告警，CUSTOM-自定义告警")
  @JsonProperty(JSON_PROPERTY_ALERT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AlertTypeEnum getAlertType() {
    return alertType;
  }


  @JsonProperty(JSON_PROPERTY_ALERT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAlertType(AlertTypeEnum alertType) {
    this.alertType = alertType;
  }


  public AlertUpdateParam content(String content) {
    this.content = content;
    return this;
  }

   /**
   * 告警内容
   * @return content
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "监控对象：${source} ${alert_source} 监控指标：${metric} 触发条件：${condition}", required = true, value = "告警内容")
  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getContent() {
    return content;
  }


  @JsonProperty(JSON_PROPERTY_CONTENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContent(String content) {
    this.content = content;
  }


  public AlertUpdateParam id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * 告警规则id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "告警规则id")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(Long id) {
    this.id = id;
  }


  public AlertUpdateParam name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 告警名称
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "CPU使用率告警", required = true, value = "告警名称")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public AlertUpdateParam notifyRecovered(Boolean notifyRecovered) {
    this.notifyRecovered = notifyRecovered;
    return this;
  }

   /**
   * 恢复是否发送通知:true-是, false-否
   * @return notifyRecovered
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "false", required = true, value = "恢复是否发送通知:true-是, false-否")
  @JsonProperty(JSON_PROPERTY_NOTIFY_RECOVERED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getNotifyRecovered() {
    return notifyRecovered;
  }


  @JsonProperty(JSON_PROPERTY_NOTIFY_RECOVERED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNotifyRecovered(Boolean notifyRecovered) {
    this.notifyRecovered = notifyRecovered;
  }


  public AlertUpdateParam recoverNotification(String recoverNotification) {
    this.recoverNotification = recoverNotification;
    return this;
  }

   /**
   * 恢复通知内容
   * @return recoverNotification
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "恢复通知内容")
  @JsonProperty(JSON_PROPERTY_RECOVER_NOTIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRecoverNotification() {
    return recoverNotification;
  }


  @JsonProperty(JSON_PROPERTY_RECOVER_NOTIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecoverNotification(String recoverNotification) {
    this.recoverNotification = recoverNotification;
  }


  public AlertUpdateParam tagSet(List<String> tagSet) {
    this.tagSet = tagSet;
    return this;
  }

  public AlertUpdateParam addTagSetItem(String tagSetItem) {
    if (this.tagSet == null) {
      this.tagSet = new ArrayList<>();
    }
    this.tagSet.add(tagSetItem);
    return this;
  }

   /**
   * 规则标签
   * @return tagSet
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "foo,bar", value = "规则标签")
  @JsonProperty(JSON_PROPERTY_TAG_SET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getTagSet() {
    return tagSet;
  }


  @JsonProperty(JSON_PROPERTY_TAG_SET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTagSet(List<String> tagSet) {
    this.tagSet = tagSet;
  }


  public AlertUpdateParam triggerRule(Object triggerRule) {
    this.triggerRule = triggerRule;
    return this;
  }

   /**
   * 触发规则
   * @return triggerRule
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "触发规则")
  @JsonProperty(JSON_PROPERTY_TRIGGER_RULE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getTriggerRule() {
    return triggerRule;
  }


  @JsonProperty(JSON_PROPERTY_TRIGGER_RULE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTriggerRule(Object triggerRule) {
    this.triggerRule = triggerRule;
  }


  /**
   * Return true if this AlertUpdateParam object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlertUpdateParam alertUpdateParam = (AlertUpdateParam) o;
    return Objects.equals(this.alertNotifies, alertUpdateParam.alertNotifies) &&
        Objects.equals(this.alertType, alertUpdateParam.alertType) &&
        Objects.equals(this.content, alertUpdateParam.content) &&
        Objects.equals(this.id, alertUpdateParam.id) &&
        Objects.equals(this.name, alertUpdateParam.name) &&
        Objects.equals(this.notifyRecovered, alertUpdateParam.notifyRecovered) &&
        Objects.equals(this.recoverNotification, alertUpdateParam.recoverNotification) &&
        Objects.equals(this.tagSet, alertUpdateParam.tagSet) &&
        Objects.equals(this.triggerRule, alertUpdateParam.triggerRule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alertNotifies, alertType, content, id, name, notifyRecovered, recoverNotification, tagSet, triggerRule);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlertUpdateParam {\n");
    sb.append("    alertNotifies: ").append(toIndentedString(alertNotifies)).append("\n");
    sb.append("    alertType: ").append(toIndentedString(alertType)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    notifyRecovered: ").append(toIndentedString(notifyRecovered)).append("\n");
    sb.append("    recoverNotification: ").append(toIndentedString(recoverNotification)).append("\n");
    sb.append("    tagSet: ").append(toIndentedString(tagSet)).append("\n");
    sb.append("    triggerRule: ").append(toIndentedString(triggerRule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

