/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.dtsre.api.v1.client.model.DataPermission;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.dtsre.api.v1.client.JSON;


/**
 * DataRoleUpdate
 */
@JsonPropertyOrder({
  DataRoleUpdate.JSON_PROPERTY_DATA_PERMISSIONS,
  DataRoleUpdate.JSON_PROPERTY_ROLE_DESC,
  DataRoleUpdate.JSON_PROPERTY_ROLE_ID,
  DataRoleUpdate.JSON_PROPERTY_ROLE_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-19T14:34:25.795+08:00[Asia/Shanghai]")
public class DataRoleUpdate {
  public static final String JSON_PROPERTY_DATA_PERMISSIONS = "dataPermissions";
  private List<DataPermission> dataPermissions = null;

  public static final String JSON_PROPERTY_ROLE_DESC = "roleDesc";
  private String roleDesc;

  public static final String JSON_PROPERTY_ROLE_ID = "roleId";
  private Long roleId;

  public static final String JSON_PROPERTY_ROLE_NAME = "roleName";
  private String roleName;

  public DataRoleUpdate() { 
  }

  public DataRoleUpdate dataPermissions(List<DataPermission> dataPermissions) {
    this.dataPermissions = dataPermissions;
    return this;
  }

  public DataRoleUpdate addDataPermissionsItem(DataPermission dataPermissionsItem) {
    if (this.dataPermissions == null) {
      this.dataPermissions = new ArrayList<>();
    }
    this.dataPermissions.add(dataPermissionsItem);
    return this;
  }

   /**
   * 功能Id列表
   * @return dataPermissions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "功能Id列表")
  @JsonProperty(JSON_PROPERTY_DATA_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DataPermission> getDataPermissions() {
    return dataPermissions;
  }


  @JsonProperty(JSON_PROPERTY_DATA_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataPermissions(List<DataPermission> dataPermissions) {
    this.dataPermissions = dataPermissions;
  }


  public DataRoleUpdate roleDesc(String roleDesc) {
    this.roleDesc = roleDesc;
    return this;
  }

   /**
   * 角色描述
   * @return roleDesc
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "userName", required = true, value = "角色描述")
  @JsonProperty(JSON_PROPERTY_ROLE_DESC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRoleDesc() {
    return roleDesc;
  }


  @JsonProperty(JSON_PROPERTY_ROLE_DESC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRoleDesc(String roleDesc) {
    this.roleDesc = roleDesc;
  }


  public DataRoleUpdate roleId(Long roleId) {
    this.roleId = roleId;
    return this;
  }

   /**
   * 角色id
   * @return roleId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "角色id")
  @JsonProperty(JSON_PROPERTY_ROLE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getRoleId() {
    return roleId;
  }


  @JsonProperty(JSON_PROPERTY_ROLE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRoleId(Long roleId) {
    this.roleId = roleId;
  }


  public DataRoleUpdate roleName(String roleName) {
    this.roleName = roleName;
    return this;
  }

   /**
   * 角色名称
   * @return roleName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "userName", required = true, value = "角色名称")
  @JsonProperty(JSON_PROPERTY_ROLE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRoleName() {
    return roleName;
  }


  @JsonProperty(JSON_PROPERTY_ROLE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRoleName(String roleName) {
    this.roleName = roleName;
  }


  /**
   * Return true if this DataRoleUpdate object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataRoleUpdate dataRoleUpdate = (DataRoleUpdate) o;
    return Objects.equals(this.dataPermissions, dataRoleUpdate.dataPermissions) &&
        Objects.equals(this.roleDesc, dataRoleUpdate.roleDesc) &&
        Objects.equals(this.roleId, dataRoleUpdate.roleId) &&
        Objects.equals(this.roleName, dataRoleUpdate.roleName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataPermissions, roleDesc, roleId, roleName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataRoleUpdate {\n");
    sb.append("    dataPermissions: ").append(toIndentedString(dataPermissions)).append("\n");
    sb.append("    roleDesc: ").append(toIndentedString(roleDesc)).append("\n");
    sb.append("    roleId: ").append(toIndentedString(roleId)).append("\n");
    sb.append("    roleName: ").append(toIndentedString(roleName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

