/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.dtsre.api.v1.client.model.KV;
import com.dtsre.api.v1.client.model.Tag;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.dtsre.api.v1.client.JSON;


/**
 * LogBase
 */
@JsonPropertyOrder({
  LogBase.JSON_PROPERTY_KVS,
  LogBase.JSON_PROPERTY_TAGS,
  LogBase.JSON_PROPERTY_TIMESTAMP
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-19T14:34:25.795+08:00[Asia/Shanghai]")
public class LogBase {
  public static final String JSON_PROPERTY_KVS = "kvs";
  private List<KV> kvs = null;

  public static final String JSON_PROPERTY_TAGS = "tags";
  private List<Tag> tags = null;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  private Long timestamp;

  public LogBase() { 
  }

  public LogBase kvs(List<KV> kvs) {
    this.kvs = kvs;
    return this;
  }

  public LogBase addKvsItem(KV kvsItem) {
    if (this.kvs == null) {
      this.kvs = new ArrayList<>();
    }
    this.kvs.add(kvsItem);
    return this;
  }

   /**
   * 键值对集合
   * @return kvs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "键值对集合")
  @JsonProperty(JSON_PROPERTY_KVS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<KV> getKvs() {
    return kvs;
  }


  @JsonProperty(JSON_PROPERTY_KVS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKvs(List<KV> kvs) {
    this.kvs = kvs;
  }


  public LogBase tags(List<Tag> tags) {
    this.tags = tags;
    return this;
  }

  public LogBase addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * 标签
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "标签")
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Tag> getTags() {
    return tags;
  }


  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(List<Tag> tags) {
    this.tags = tags;
  }


  public LogBase timestamp(Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * 时间戳，单位：毫秒
   * @return timestamp
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1651110830000", required = true, value = "时间戳，单位：毫秒")
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTimestamp() {
    return timestamp;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }


  /**
   * Return true if this LogBase object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogBase logBase = (LogBase) o;
    return Objects.equals(this.kvs, logBase.kvs) &&
        Objects.equals(this.tags, logBase.tags) &&
        Objects.equals(this.timestamp, logBase.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kvs, tags, timestamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogBase {\n");
    sb.append("    kvs: ").append(toIndentedString(kvs)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

