/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.dtsre.api.v1.client.JSON;


/**
 * LogSearchParam
 */
@JsonPropertyOrder({
  LogSearchParam.JSON_PROPERTY_APPNAMES,
  LogSearchParam.JSON_PROPERTY_END,
  LogSearchParam.JSON_PROPERTY_PAGE_NUMBER,
  LogSearchParam.JSON_PROPERTY_PAGE_SIZE,
  LogSearchParam.JSON_PROPERTY_QUERY_TEXT,
  LogSearchParam.JSON_PROPERTY_SELECT_FIELDS,
  LogSearchParam.JSON_PROPERTY_SORT,
  LogSearchParam.JSON_PROPERTY_START
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-19T14:34:25.795+08:00[Asia/Shanghai]")
public class LogSearchParam {
  public static final String JSON_PROPERTY_APPNAMES = "appnames";
  private List<String> appnames = new ArrayList<>();

  public static final String JSON_PROPERTY_END = "end";
  private Long end;

  public static final String JSON_PROPERTY_PAGE_NUMBER = "pageNumber";
  private Integer pageNumber;

  public static final String JSON_PROPERTY_PAGE_SIZE = "pageSize";
  private Integer pageSize;

  public static final String JSON_PROPERTY_QUERY_TEXT = "queryText";
  private String queryText;

  public static final String JSON_PROPERTY_SELECT_FIELDS = "selectFields";
  private List<String> selectFields = null;

  public static final String JSON_PROPERTY_SORT = "sort";
  private String sort;

  public static final String JSON_PROPERTY_START = "start";
  private Long start;

  public LogSearchParam() { 
  }

  public LogSearchParam appnames(List<String> appnames) {
    this.appnames = appnames;
    return this;
  }

  public LogSearchParam addAppnamesItem(String appnamesItem) {
    this.appnames.add(appnamesItem);
    return this;
  }

   /**
   * 数据集
   * @return appnames
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "数据集")
  @JsonProperty(JSON_PROPERTY_APPNAMES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getAppnames() {
    return appnames;
  }


  @JsonProperty(JSON_PROPERTY_APPNAMES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAppnames(List<String> appnames) {
    this.appnames = appnames;
  }


  public LogSearchParam end(Long end) {
    this.end = end;
    return this;
  }

   /**
   * 结束时间，Unix时间戳，单位：秒
   * @return end
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1651127345", required = true, value = "结束时间，Unix时间戳，单位：秒")
  @JsonProperty(JSON_PROPERTY_END)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getEnd() {
    return end;
  }


  @JsonProperty(JSON_PROPERTY_END)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEnd(Long end) {
    this.end = end;
  }


  public LogSearchParam pageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
    return this;
  }

   /**
   * 页码
   * @return pageNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "页码")
  @JsonProperty(JSON_PROPERTY_PAGE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPageNumber() {
    return pageNumber;
  }


  @JsonProperty(JSON_PROPERTY_PAGE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
  }


  public LogSearchParam pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * 每页大小
   * @return pageSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "每页大小")
  @JsonProperty(JSON_PROPERTY_PAGE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPageSize() {
    return pageSize;
  }


  @JsonProperty(JSON_PROPERTY_PAGE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }


  public LogSearchParam queryText(String queryText) {
    this.queryText = queryText;
    return this;
  }

   /**
   * 查询条件
   * @return queryText
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "查询条件")
  @JsonProperty(JSON_PROPERTY_QUERY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQueryText() {
    return queryText;
  }


  @JsonProperty(JSON_PROPERTY_QUERY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQueryText(String queryText) {
    this.queryText = queryText;
  }


  public LogSearchParam selectFields(List<String> selectFields) {
    this.selectFields = selectFields;
    return this;
  }

  public LogSearchParam addSelectFieldsItem(String selectFieldsItem) {
    if (this.selectFields == null) {
      this.selectFields = new ArrayList<>();
    }
    this.selectFields.add(selectFieldsItem);
    return this;
  }

   /**
   * 查询字段
   * @return selectFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "查询字段")
  @JsonProperty(JSON_PROPERTY_SELECT_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSelectFields() {
    return selectFields;
  }


  @JsonProperty(JSON_PROPERTY_SELECT_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelectFields(List<String> selectFields) {
    this.selectFields = selectFields;
  }


  public LogSearchParam sort(String sort) {
    this.sort = sort;
    return this;
  }

   /**
   * asc/desc,默认根据时间倒序
   * @return sort
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "asc/desc,默认根据时间倒序")
  @JsonProperty(JSON_PROPERTY_SORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSort() {
    return sort;
  }


  @JsonProperty(JSON_PROPERTY_SORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSort(String sort) {
    this.sort = sort;
  }


  public LogSearchParam start(Long start) {
    this.start = start;
    return this;
  }

   /**
   * 开始时间，Unix时间戳，单位：秒
   * @return start
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1651127245", required = true, value = "开始时间，Unix时间戳，单位：秒")
  @JsonProperty(JSON_PROPERTY_START)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getStart() {
    return start;
  }


  @JsonProperty(JSON_PROPERTY_START)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStart(Long start) {
    this.start = start;
  }


  /**
   * Return true if this LogSearchParam object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogSearchParam logSearchParam = (LogSearchParam) o;
    return Objects.equals(this.appnames, logSearchParam.appnames) &&
        Objects.equals(this.end, logSearchParam.end) &&
        Objects.equals(this.pageNumber, logSearchParam.pageNumber) &&
        Objects.equals(this.pageSize, logSearchParam.pageSize) &&
        Objects.equals(this.queryText, logSearchParam.queryText) &&
        Objects.equals(this.selectFields, logSearchParam.selectFields) &&
        Objects.equals(this.sort, logSearchParam.sort) &&
        Objects.equals(this.start, logSearchParam.start);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appnames, end, pageNumber, pageSize, queryText, selectFields, sort, start);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogSearchParam {\n");
    sb.append("    appnames: ").append(toIndentedString(appnames)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    queryText: ").append(toIndentedString(queryText)).append("\n");
    sb.append("    selectFields: ").append(toIndentedString(selectFields)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

