/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.dtsre.api.v1.client.model.LogRecord;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.dtsre.api.v1.client.JSON;


/**
 * LogSendParam
 */
@JsonPropertyOrder({
  LogSendParam.JSON_PROPERTY_APPNAME,
  LogSendParam.JSON_PROPERTY_LOGS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-19T14:34:25.795+08:00[Asia/Shanghai]")
public class LogSendParam {
  public static final String JSON_PROPERTY_APPNAME = "appname";
  private String appname;

  public static final String JSON_PROPERTY_LOGS = "logs";
  private List<LogRecord> logs = null;

  public LogSendParam() { 
  }

  public LogSendParam appname(String appname) {
    this.appname = appname;
    return this;
  }

   /**
   * 数据集
   * @return appname
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "system_metrics", required = true, value = "数据集")
  @JsonProperty(JSON_PROPERTY_APPNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAppname() {
    return appname;
  }


  @JsonProperty(JSON_PROPERTY_APPNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAppname(String appname) {
    this.appname = appname;
  }


  public LogSendParam logs(List<LogRecord> logs) {
    this.logs = logs;
    return this;
  }

  public LogSendParam addLogsItem(LogRecord logsItem) {
    if (this.logs == null) {
      this.logs = new ArrayList<>();
    }
    this.logs.add(logsItem);
    return this;
  }

   /**
   * Get logs
   * @return logs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<LogRecord> getLogs() {
    return logs;
  }


  @JsonProperty(JSON_PROPERTY_LOGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogs(List<LogRecord> logs) {
    this.logs = logs;
  }


  /**
   * Return true if this LogSendParam object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogSendParam logSendParam = (LogSendParam) o;
    return Objects.equals(this.appname, logSendParam.appname) &&
        Objects.equals(this.logs, logSendParam.logs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appname, logs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogSendParam {\n");
    sb.append("    appname: ").append(toIndentedString(appname)).append("\n");
    sb.append("    logs: ").append(toIndentedString(logs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

