/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.dtsre.api.v1.client.model.LogBase;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.dtsre.api.v1.client.JSON;


/**
 * MetricSendParam
 */
@JsonPropertyOrder({
  MetricSendParam.JSON_PROPERTY_APPNAME,
  MetricSendParam.JSON_PROPERTY_METRICS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-19T14:34:25.795+08:00[Asia/Shanghai]")
public class MetricSendParam {
  public static final String JSON_PROPERTY_APPNAME = "appname";
  private String appname;

  public static final String JSON_PROPERTY_METRICS = "metrics";
  private List<LogBase> metrics = null;

  public MetricSendParam() { 
  }

  public MetricSendParam appname(String appname) {
    this.appname = appname;
    return this;
  }

   /**
   * 数据集
   * @return appname
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "system_metrics", required = true, value = "数据集")
  @JsonProperty(JSON_PROPERTY_APPNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAppname() {
    return appname;
  }


  @JsonProperty(JSON_PROPERTY_APPNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAppname(String appname) {
    this.appname = appname;
  }


  public MetricSendParam metrics(List<LogBase> metrics) {
    this.metrics = metrics;
    return this;
  }

  public MetricSendParam addMetricsItem(LogBase metricsItem) {
    if (this.metrics == null) {
      this.metrics = new ArrayList<>();
    }
    this.metrics.add(metricsItem);
    return this;
  }

   /**
   * Get metrics
   * @return metrics
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_METRICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<LogBase> getMetrics() {
    return metrics;
  }


  @JsonProperty(JSON_PROPERTY_METRICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetrics(List<LogBase> metrics) {
    this.metrics = metrics;
  }


  /**
   * Return true if this MetricSendParam object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetricSendParam metricSendParam = (MetricSendParam) o;
    return Objects.equals(this.appname, metricSendParam.appname) &&
        Objects.equals(this.metrics, metricSendParam.metrics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appname, metrics);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetricSendParam {\n");
    sb.append("    appname: ").append(toIndentedString(appname)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

