/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.dtsre.api.v1.client.JSON;


/**
 * OpenDataItemVO
 */
@JsonPropertyOrder({
  OpenDataItemVO.JSON_PROPERTY_PERMISSION_ID,
  OpenDataItemVO.JSON_PROPERTY_TAG_SET,
  OpenDataItemVO.JSON_PROPERTY_TYPE,
  OpenDataItemVO.JSON_PROPERTY_TYPE_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-19T14:34:25.795+08:00[Asia/Shanghai]")
public class OpenDataItemVO {
  public static final String JSON_PROPERTY_PERMISSION_ID = "permissionId";
  private Long permissionId;

  public static final String JSON_PROPERTY_TAG_SET = "tagSet";
  private List<String> tagSet = null;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_TYPE_NAME = "typeName";
  private String typeName;

  public OpenDataItemVO() { 
  }

  public OpenDataItemVO permissionId(Long permissionId) {
    this.permissionId = permissionId;
    return this;
  }

   /**
   * 数据业务id
   * @return permissionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "数据业务id")
  @JsonProperty(JSON_PROPERTY_PERMISSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPermissionId() {
    return permissionId;
  }


  @JsonProperty(JSON_PROPERTY_PERMISSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPermissionId(Long permissionId) {
    this.permissionId = permissionId;
  }


  public OpenDataItemVO tagSet(List<String> tagSet) {
    this.tagSet = tagSet;
    return this;
  }

  public OpenDataItemVO addTagSetItem(String tagSetItem) {
    if (this.tagSet == null) {
      this.tagSet = new ArrayList<>();
    }
    this.tagSet.add(tagSetItem);
    return this;
  }

   /**
   * 业务数据子集
   * @return tagSet
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "业务数据子集")
  @JsonProperty(JSON_PROPERTY_TAG_SET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getTagSet() {
    return tagSet;
  }


  @JsonProperty(JSON_PROPERTY_TAG_SET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTagSet(List<String> tagSet) {
    this.tagSet = tagSet;
  }


  public OpenDataItemVO type(String type) {
    this.type = type;
    return this;
  }

   /**
   * 数据业务类型
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "数据业务类型")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }


  public OpenDataItemVO typeName(String typeName) {
    this.typeName = typeName;
    return this;
  }

   /**
   * 数据业务类型名称
   * @return typeName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "数据业务类型名称")
  @JsonProperty(JSON_PROPERTY_TYPE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTypeName() {
    return typeName;
  }


  @JsonProperty(JSON_PROPERTY_TYPE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTypeName(String typeName) {
    this.typeName = typeName;
  }


  /**
   * Return true if this OpenDataItemVO object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenDataItemVO openDataItemVO = (OpenDataItemVO) o;
    return Objects.equals(this.permissionId, openDataItemVO.permissionId) &&
        Objects.equals(this.tagSet, openDataItemVO.tagSet) &&
        Objects.equals(this.type, openDataItemVO.type) &&
        Objects.equals(this.typeName, openDataItemVO.typeName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(permissionId, tagSet, type, typeName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenDataItemVO {\n");
    sb.append("    permissionId: ").append(toIndentedString(permissionId)).append("\n");
    sb.append("    tagSet: ").append(toIndentedString(tagSet)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    typeName: ").append(toIndentedString(typeName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

