/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.dtsre.api.v1.client.model.TenantUserListVo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.dtsre.api.v1.client.JSON;


/**
 * PagerOfTenantUserListVo
 */
@JsonPropertyOrder({
  PagerOfTenantUserListVo.JSON_PROPERTY_CURRENT_PAGE_NUMBER,
  PagerOfTenantUserListVo.JSON_PROPERTY_DATA,
  PagerOfTenantUserListVo.JSON_PROPERTY_HAS_NEXT,
  PagerOfTenantUserListVo.JSON_PROPERTY_HAS_PREV,
  PagerOfTenantUserListVo.JSON_PROPERTY_PER_PAGE_SIZE,
  PagerOfTenantUserListVo.JSON_PROPERTY_TOTAL_ELEMENTS,
  PagerOfTenantUserListVo.JSON_PROPERTY_TOTAL_PAGES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-19T14:34:25.795+08:00[Asia/Shanghai]")
public class PagerOfTenantUserListVo {
  public static final String JSON_PROPERTY_CURRENT_PAGE_NUMBER = "currentPageNumber";
  private Integer currentPageNumber;

  public static final String JSON_PROPERTY_DATA = "data";
  private List<TenantUserListVo> data = null;

  public static final String JSON_PROPERTY_HAS_NEXT = "hasNext";
  private Boolean hasNext;

  public static final String JSON_PROPERTY_HAS_PREV = "hasPrev";
  private Boolean hasPrev;

  public static final String JSON_PROPERTY_PER_PAGE_SIZE = "perPageSize";
  private Integer perPageSize;

  public static final String JSON_PROPERTY_TOTAL_ELEMENTS = "totalElements";
  private Long totalElements;

  public static final String JSON_PROPERTY_TOTAL_PAGES = "totalPages";
  private Long totalPages;

  public PagerOfTenantUserListVo() { 
  }

  public PagerOfTenantUserListVo currentPageNumber(Integer currentPageNumber) {
    this.currentPageNumber = currentPageNumber;
    return this;
  }

   /**
   * Get currentPageNumber
   * @return currentPageNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CURRENT_PAGE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCurrentPageNumber() {
    return currentPageNumber;
  }


  @JsonProperty(JSON_PROPERTY_CURRENT_PAGE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrentPageNumber(Integer currentPageNumber) {
    this.currentPageNumber = currentPageNumber;
  }


  public PagerOfTenantUserListVo data(List<TenantUserListVo> data) {
    this.data = data;
    return this;
  }

  public PagerOfTenantUserListVo addDataItem(TenantUserListVo dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TenantUserListVo> getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(List<TenantUserListVo> data) {
    this.data = data;
  }


  public PagerOfTenantUserListVo hasNext(Boolean hasNext) {
    this.hasNext = hasNext;
    return this;
  }

   /**
   * Get hasNext
   * @return hasNext
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HAS_NEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasNext() {
    return hasNext;
  }


  @JsonProperty(JSON_PROPERTY_HAS_NEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasNext(Boolean hasNext) {
    this.hasNext = hasNext;
  }


  public PagerOfTenantUserListVo hasPrev(Boolean hasPrev) {
    this.hasPrev = hasPrev;
    return this;
  }

   /**
   * Get hasPrev
   * @return hasPrev
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HAS_PREV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasPrev() {
    return hasPrev;
  }


  @JsonProperty(JSON_PROPERTY_HAS_PREV)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasPrev(Boolean hasPrev) {
    this.hasPrev = hasPrev;
  }


  public PagerOfTenantUserListVo perPageSize(Integer perPageSize) {
    this.perPageSize = perPageSize;
    return this;
  }

   /**
   * Get perPageSize
   * @return perPageSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PER_PAGE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPerPageSize() {
    return perPageSize;
  }


  @JsonProperty(JSON_PROPERTY_PER_PAGE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPerPageSize(Integer perPageSize) {
    this.perPageSize = perPageSize;
  }


  public PagerOfTenantUserListVo totalElements(Long totalElements) {
    this.totalElements = totalElements;
    return this;
  }

   /**
   * Get totalElements
   * @return totalElements
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_ELEMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalElements() {
    return totalElements;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_ELEMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalElements(Long totalElements) {
    this.totalElements = totalElements;
  }


  public PagerOfTenantUserListVo totalPages(Long totalPages) {
    this.totalPages = totalPages;
    return this;
  }

   /**
   * Get totalPages
   * @return totalPages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_PAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalPages() {
    return totalPages;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_PAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalPages(Long totalPages) {
    this.totalPages = totalPages;
  }


  /**
   * Return true if this PagerOfTenantUserListVo object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PagerOfTenantUserListVo pagerOfTenantUserListVo = (PagerOfTenantUserListVo) o;
    return Objects.equals(this.currentPageNumber, pagerOfTenantUserListVo.currentPageNumber) &&
        Objects.equals(this.data, pagerOfTenantUserListVo.data) &&
        Objects.equals(this.hasNext, pagerOfTenantUserListVo.hasNext) &&
        Objects.equals(this.hasPrev, pagerOfTenantUserListVo.hasPrev) &&
        Objects.equals(this.perPageSize, pagerOfTenantUserListVo.perPageSize) &&
        Objects.equals(this.totalElements, pagerOfTenantUserListVo.totalElements) &&
        Objects.equals(this.totalPages, pagerOfTenantUserListVo.totalPages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentPageNumber, data, hasNext, hasPrev, perPageSize, totalElements, totalPages);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PagerOfTenantUserListVo {\n");
    sb.append("    currentPageNumber: ").append(toIndentedString(currentPageNumber)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    hasNext: ").append(toIndentedString(hasNext)).append("\n");
    sb.append("    hasPrev: ").append(toIndentedString(hasPrev)).append("\n");
    sb.append("    perPageSize: ").append(toIndentedString(perPageSize)).append("\n");
    sb.append("    totalElements: ").append(toIndentedString(totalElements)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

