/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.dtsre.api.v1.client.JSON;


/**
 * TimeseriesVO
 */
@JsonPropertyOrder({
  TimeseriesVO.JSON_PROPERTY_INTERVAL,
  TimeseriesVO.JSON_PROPERTY_POINTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-19T14:34:25.795+08:00[Asia/Shanghai]")
public class TimeseriesVO {
  public static final String JSON_PROPERTY_INTERVAL = "interval";
  private Long interval;

  public static final String JSON_PROPERTY_POINTS = "points";
  private List<Map<String, Object>> points = null;

  public TimeseriesVO() { 
  }

  public TimeseriesVO interval(Long interval) {
    this.interval = interval;
    return this;
  }

   /**
   * 时间间隔，单位：秒
   * @return interval
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "60", value = "时间间隔，单位：秒")
  @JsonProperty(JSON_PROPERTY_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getInterval() {
    return interval;
  }


  @JsonProperty(JSON_PROPERTY_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInterval(Long interval) {
    this.interval = interval;
  }


  public TimeseriesVO points(List<Map<String, Object>> points) {
    this.points = points;
    return this;
  }

  public TimeseriesVO addPointsItem(Map<String, Object> pointsItem) {
    if (this.points == null) {
      this.points = new ArrayList<>();
    }
    this.points.add(pointsItem);
    return this;
  }

   /**
   * 时间序列的点集合
   * @return points
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "时间序列的点集合")
  @JsonProperty(JSON_PROPERTY_POINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Map<String, Object>> getPoints() {
    return points;
  }


  @JsonProperty(JSON_PROPERTY_POINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPoints(List<Map<String, Object>> points) {
    this.points = points;
  }


  /**
   * Return true if this TimeseriesVO object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeseriesVO timeseriesVO = (TimeseriesVO) o;
    return Objects.equals(this.interval, timeseriesVO.interval) &&
        Objects.equals(this.points, timeseriesVO.points);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interval, points);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeseriesVO {\n");
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("    points: ").append(toIndentedString(points)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

