/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.dtsre.api.v1.client.JSON;


/**
 * UnitDTO
 */
@JsonPropertyOrder({
  UnitDTO.JSON_PROPERTY_CODE,
  UnitDTO.JSON_PROPERTY_FAMILY,
  UnitDTO.JSON_PROPERTY_ID,
  UnitDTO.JSON_PROPERTY_NAME,
  UnitDTO.JSON_PROPERTY_PLURAL,
  UnitDTO.JSON_PROPERTY_SHORT_NAME,
  UnitDTO.JSON_PROPERTY_SINGULAR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-19T14:34:25.795+08:00[Asia/Shanghai]")
public class UnitDTO {
  public static final String JSON_PROPERTY_CODE = "code";
  private String code;

  public static final String JSON_PROPERTY_FAMILY = "family";
  private String family;

  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_PLURAL = "plural";
  private String plural;

  public static final String JSON_PROPERTY_SHORT_NAME = "shortName";
  private String shortName;

  public static final String JSON_PROPERTY_SINGULAR = "singular";
  private String singular;

  public UnitDTO() { 
  }

  public UnitDTO code(String code) {
    this.code = code;
    return this;
  }

   /**
   * 单位转换标识
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "单位转换标识")
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(String code) {
    this.code = code;
  }


  public UnitDTO family(String family) {
    this.family = family;
    return this;
  }

   /**
   * 单位所属大类
   * @return family
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "单位所属大类")
  @JsonProperty(JSON_PROPERTY_FAMILY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFamily() {
    return family;
  }


  @JsonProperty(JSON_PROPERTY_FAMILY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFamily(String family) {
    this.family = family;
  }


  public UnitDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * 单位id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "单位id")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public UnitDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 单位中文名：字节
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "单位中文名：字节")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public UnitDTO plural(String plural) {
    this.plural = plural;
    return this;
  }

   /**
   * 复制形式：bytes
   * @return plural
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "复制形式：bytes")
  @JsonProperty(JSON_PROPERTY_PLURAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPlural() {
    return plural;
  }


  @JsonProperty(JSON_PROPERTY_PLURAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlural(String plural) {
    this.plural = plural;
  }


  public UnitDTO shortName(String shortName) {
    this.shortName = shortName;
    return this;
  }

   /**
   * 简写：B
   * @return shortName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "简写：B")
  @JsonProperty(JSON_PROPERTY_SHORT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getShortName() {
    return shortName;
  }


  @JsonProperty(JSON_PROPERTY_SHORT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShortName(String shortName) {
    this.shortName = shortName;
  }


  public UnitDTO singular(String singular) {
    this.singular = singular;
    return this;
  }

   /**
   * 单数形式：byte
   * @return singular
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "单数形式：byte")
  @JsonProperty(JSON_PROPERTY_SINGULAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSingular() {
    return singular;
  }


  @JsonProperty(JSON_PROPERTY_SINGULAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSingular(String singular) {
    this.singular = singular;
  }


  /**
   * Return true if this UnitDTO object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnitDTO unitDTO = (UnitDTO) o;
    return Objects.equals(this.code, unitDTO.code) &&
        Objects.equals(this.family, unitDTO.family) &&
        Objects.equals(this.id, unitDTO.id) &&
        Objects.equals(this.name, unitDTO.name) &&
        Objects.equals(this.plural, unitDTO.plural) &&
        Objects.equals(this.shortName, unitDTO.shortName) &&
        Objects.equals(this.singular, unitDTO.singular);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, family, id, name, plural, shortName, singular);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnitDTO {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    plural: ").append(toIndentedString(plural)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    singular: ").append(toIndentedString(singular)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

