/*
 * 开放API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: V1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dtsre.api.v1.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.dtsre.api.v1.client.JSON;


/**
 * UserRoleAdd
 */
@JsonPropertyOrder({
  UserRoleAdd.JSON_PROPERTY_ROLE_IDS,
  UserRoleAdd.JSON_PROPERTY_USER_IDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-19T14:34:25.795+08:00[Asia/Shanghai]")
public class UserRoleAdd {
  public static final String JSON_PROPERTY_ROLE_IDS = "roleIds";
  private List<Long> roleIds = new ArrayList<>();

  public static final String JSON_PROPERTY_USER_IDS = "userIds";
  private List<Long> userIds = new ArrayList<>();

  public UserRoleAdd() { 
  }

  public UserRoleAdd roleIds(List<Long> roleIds) {
    this.roleIds = roleIds;
    return this;
  }

  public UserRoleAdd addRoleIdsItem(Long roleIdsItem) {
    this.roleIds.add(roleIdsItem);
    return this;
  }

   /**
   * 角色id列表
   * @return roleIds
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "userName", required = true, value = "角色id列表")
  @JsonProperty(JSON_PROPERTY_ROLE_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Long> getRoleIds() {
    return roleIds;
  }


  @JsonProperty(JSON_PROPERTY_ROLE_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRoleIds(List<Long> roleIds) {
    this.roleIds = roleIds;
  }


  public UserRoleAdd userIds(List<Long> userIds) {
    this.userIds = userIds;
    return this;
  }

  public UserRoleAdd addUserIdsItem(Long userIdsItem) {
    this.userIds.add(userIdsItem);
    return this;
  }

   /**
   * 用户id列表
   * @return userIds
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "[1, 2, 3]", required = true, value = "用户id列表")
  @JsonProperty(JSON_PROPERTY_USER_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Long> getUserIds() {
    return userIds;
  }


  @JsonProperty(JSON_PROPERTY_USER_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserIds(List<Long> userIds) {
    this.userIds = userIds;
  }


  /**
   * Return true if this UserRoleAdd object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserRoleAdd userRoleAdd = (UserRoleAdd) o;
    return Objects.equals(this.roleIds, userRoleAdd.roleIds) &&
        Objects.equals(this.userIds, userRoleAdd.userIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roleIds, userIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserRoleAdd {\n");
    sb.append("    roleIds: ").append(toIndentedString(roleIds)).append("\n");
    sb.append("    userIds: ").append(toIndentedString(userIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

